@ echo off
SET APPLICATION_NAME=
SET APPLICATION_PATH=%~dp0

SET CONF_NAME=*.conf
SET PAHT_FOLDER_RELATIVE=src\my_app_name\conf\
SET PATH_CONF_FILE=%APPLICATION_PATH%%PAHT_FOLDER_RELATIVE%%CONF_NAME%


SET DESTINATION_FOLDER_RELATIVE=dist\package_tutorial\conf
SET DESTINATION_FOLDER_ABSOLUTE=%APPLICATION_PATH%%DESTINATION_FOLDER_RELATIVE%


ECHO %APPLICATION_PATH%
ECHO %PATH_CONF_FILE%
ECHO %DESTINATION_FOLDER_ABSOLUTE%
ECHO 'pip package is OK -- /dist/my_package_MY_APP_NAME_HERE-0.0.1-py3-none-any.whl'
py -m build